name: Evaluation API (robust JSONL append)

on:
  repository_dispatch:
    types: [evaluate_submission]

permissions:
  contents: write
  actions: read

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Read payload directly from the event JSON so it's always valid
      - name: Save submission payload (from event file)
        run: |
          set -euo pipefail
          jq -c '.client_payload // {}' "$GITHUB_EVENT_PATH" > submission.json
          echo "submission.json:"
          jq . submission.json

      # Build one JSON line, append safely to repos.jsonl, then print that exact line
      - name: Append to repos.jsonl (safe)
        run: |
          set -euo pipefail
          # Ensure log file exists (create if missing)
          [ -f repos.jsonl ] || : > repos.jsonl

          ts=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

          # Build the new JSON line in a temp file (compact, single-line JSON)
          jq -c --arg ts "$ts" '(. // {}) + {timestamp: $ts}' submission.json > line.json

          # Append the line and a newline explicitly (avoid partial/merged lines)
          cat line.json >> repos.jsonl
          printf "\n" >> repos.jsonl

          echo "Last appended line (parsed):"
          cat line.json | jq .

      - name: Commit repos.jsonl
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "log: accept evaluate_submission"
          file_pattern: repos.jsonl

      - name: Done
        run: echo "✅ Evaluator accepted and logged the submission"
