name: Evaluation API (no validations)

on:
  repository_dispatch:
    types: [evaluate_submission]

permissions:
  contents: write
  actions: read

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout grader repo
        uses: actions/checkout@v4

      - name: Save submission payload
        run: |
          echo '${{ toJson(github.event.client_payload) }}' > submission.json
          echo "Submission received:"
          cat submission.json

      # 👇 Unconditional log; no tasks.json checks, no format checks
      - name: Append to repos.jsonl
        run: |
          [ -f repos.jsonl ] || : > repos.jsonl
          ts=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          jq --arg ts "$ts" '. + {timestamp: $ts}' submission.json >> repos.jsonl
          tail -n 1 repos.jsonl | jq .

      - name: Commit repos.jsonl
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "log: accept submission (no validations)"
          file_pattern: repos.jsonl

      - name: Done
        run: echo "✅ Evaluator accepted submission (no validations)"
