name: Evaluation API (robust, no validations)

on:
  repository_dispatch:
    types: [evaluate_submission]

permissions:
  contents: write
  actions: read

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Optional: quick peek at the raw event for troubleshooting
      - name: Debug event (optional)
        run: |
          set -euo pipefail
          echo "Event path: $GITHUB_EVENT_PATH"
          head -n 50 "$GITHUB_EVENT_PATH" || true
          echo "--- client_payload ---"
          jq '.client_payload' "$GITHUB_EVENT_PATH" || true

      # Always produce a valid JSON object for the submission
      - name: Save submission payload (from event file)
        run: |
          set -euo pipefail
          # Extract .client_payload (or {} if missing) as compact JSON
          jq -c '.client_payload // {}' "$GITHUB_EVENT_PATH" > submission.json
          echo "submission.json:"
          jq . submission.json

      # Append safely to repos.jsonl (create the file if missing)
      - name: Append to repos.jsonl (safe)
        run: |
          set -euo pipefail
          [ -f repos.jsonl ] || : > repos.jsonl
          ts=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          # Coerce non-object/null to {} then add timestamp field
          jq --arg ts "$ts" '(. // {}) + {timestamp: $ts}' submission.json >> repos.jsonl
          echo "Last appended line:"
          tail -n 1 repos.jsonl | jq .

      - name: Commit repos.jsonl
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "log: accept evaluate_submission"
          file_pattern: repos.jsonl

      - name: Done
        run: echo "✅ Evaluator accepted and logged the submission"
