import fs from "node:fs";

const req = JSON.parse(fs.readFileSync("request.json", "utf8"));
const title = `Task: ${req.task} (Round ${req.round})`;
const html = `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${title}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>
  <h1>${title}</h1>
  <p>Email: ${req.email}</p>
  <p>Brief: ${req.brief ?? "N/A"}</p>
  <div id="app">Hello from Project_1</div>
</body>
</html>`;

fs.writeFileSync("index.html", html, "utf8");

const readme = `# ${title}

Deployed at: https://MVRules.github.io/Project_1/

## Brief
${req.brief ?? "N/A"}

## How it works
- This page is generated by \`scripts/generate.js\` based on \`request.json\`.
- Built and deployed via GitHub Actions.

## License
MIT
`;
fs.writeFileSync("README.md", readme, "utf8");

// Add a simple MIT license if missing
if (!fs.existsSync("LICENSE")) {
  fs.writeFileSync("LICENSE", `MIT License

Copyright (c) ${new Date().getFullYear()} MVRules

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction...`, "utf8");
}

console.log("Generated index.html and README.md");
